import { useMemo, useState } from 'react';
import { Plus } from 'lucide-react';
import type { RentalBooking, RentalBookingStatus, RentalCustomer, RentalPayment, RentalPricePlan } from './types';
import type { RentalBookingInput, RentalPaymentInput } from './useRoomRental';
import { Button, Input, Select } from './dsComponents';
import { EmptyState, ModalForm, MoneyText, PageToolbar, StatusBadge, ToolbarTabs } from './uiSystem';

type View = 'overview' | 'schedule' | 'bookings' | 'customers' | 'payments' | 'reports' | 'prices';
const today = () => new Date().toISOString().slice(0, 10);
const ymdToDmy = (value: string) => { const [y, m, d] = value.split('-'); return y && m && d ? `${d}/${m}/${y}` : value; };
const dmyKey = (value: string) => { const p = value.split('/'); return p.length === 3 ? `${p[2]}-${p[1]}-${p[0]}` : value.slice(0, 10); };
const money = (value: number) => new Intl.NumberFormat('vi-VN').format(value) + 'đ';
const statusLabel: Record<RentalBookingStatus, string> = { confirmed: 'Đã xác nhận', completed: 'Hoàn thành', cancelled: 'Đã hủy' };
const paymentState = (booking: RentalBooking, payments: RentalPayment[]) => { const paid = payments.filter(p => p.bookingId === booking.id).reduce((sum, p) => sum + p.amount, 0); return { paid, balance: Math.max(booking.amount - paid, 0), label: paid <= 0 ? 'Chưa thu' : paid < booking.amount ? `Đã thu ${money(paid)}` : 'Đã đủ' }; };
const timeOk = (value: string) => /^([01]\d|2[0-3]):[0-5]\d$/.test(value);
const mins = (value: string) => { const [h, m] = value.split(':').map(Number); return h * 60 + m; };
const defaultPlans: RentalPricePlan[] = [{ id: '', name: '90 phút — không điều hòa', amount: 60000, durationMinutes: 90, airConditioning: false, status: 'active', order: 1, note: '' }, { id: '', name: '90 phút — có điều hòa', amount: 70000, durationMinutes: 90, airConditioning: true, status: 'active', order: 2, note: '' }];

function BookingModal({ open, booking, customers, plans, saving, allBookings, onClose, onSave }: { open: boolean; booking: RentalBooking | null; customers: RentalCustomer[]; plans: RentalPricePlan[]; saving: boolean; allBookings: RentalBooking[]; onClose: () => void; onSave: (value: RentalBookingInput) => Promise<void> }) {
  const initialPlan = plans.find(p => p.status === 'active') || defaultPlans[0];
  const [name, setName] = useState(booking?.name || ''); const [customerId, setCustomerId] = useState(booking?.customerId || '');
  const [renterName, setRenterName] = useState(booking?.renterName || ''); const [renterPhone, setRenterPhone] = useState(booking?.renterPhone || '');
  const [date, setDate] = useState(booking ? dmyKey(booking.date) : today()); const [startTime, setStartTime] = useState(booking?.startTime || '09:15'); const [endTime, setEndTime] = useState(booking?.endTime || '10:45');
  const [planId, setPlanId] = useState(''); const [amount, setAmount] = useState(String(booking?.amount || initialPlan.amount)); const [air, setAir] = useState(booking?.airConditioning ? 'yes' : 'no');
  const [repeatEnd, setRepeatEnd] = useState(''); const [repeatDays, setRepeatDays] = useState<number[]>([]); const [note, setNote] = useState(booking?.note || ''); const [error, setError] = useState('');
  const chooseCustomer = (id: string) => { setCustomerId(id); const customer = customers.find(c => c.id === id); if (customer) { setRenterName(customer.name); setRenterPhone(customer.phone); } };
  const choosePlan = (id: string) => { setPlanId(id); const plan = plans.find(p => p.id === id) || defaultPlans.find(p => p.name === id); if (plan) { setAmount(String(plan.amount)); setAir(plan.airConditioning ? 'yes' : 'no'); } };
  const save = async () => { if (!name.trim() || !renterName.trim() || !renterPhone.trim()) return setError('Cần tên lịch, người thuê và số điện thoại.'); if (!date || !timeOk(startTime) || !timeOk(endTime) || mins(endTime) <= mins(startTime)) return setError('Kiểm tra lại ngày và khung giờ HH:mm.'); const dates: string[] = []; if (repeatEnd) { const end = new Date(`${repeatEnd}T12:00:00`), start = new Date(`${date}T12:00:00`); if (end < start || !repeatDays.length) return setError('Lịch lặp cần ngày kết thúc và ít nhất một thứ.'); for (let cur = new Date(start); cur <= end; cur.setDate(cur.getDate() + 1)) if (repeatDays.includes(cur.getDay() || 7)) dates.push(cur.toISOString().slice(0, 10)); }
    const proposed = dates.length ? dates : [date]; const clash = allBookings.some(item => item.id !== booking?.id && item.status !== 'cancelled' && proposed.includes(dmyKey(item.date)) && mins(startTime) < mins(item.endTime) && mins(endTime) > mins(item.startTime)); if (clash) return setError('Có ca cùng phòng trùng giờ.'); setError(''); await onSave({ id: booking?.id, seriesId: booking?.seriesId, customerId, name: name.trim(), renterName: renterName.trim(), renterPhone: renterPhone.trim(), roomName: booking?.roomName || 'Phòng học', date: ymdToDmy(date), startTime, endTime, airConditioning: air === 'yes', amount: Number(amount) || 0, status: booking?.status || 'confirmed', note, repeatDates: dates, repeatRule: dates.length ? `weekly:${repeatDays.join(',')}` : '', createSeries: dates.length > 0 }); onClose(); };
  return <ModalForm open={open} onClose={onClose} onSubmit={save} title={booking ? 'Cập nhật ca thuê' : 'Tạo lịch thuê'} subtitle={booking ? 'Chỉ sửa ca được chọn; giao dịch đã thu được giữ nguyên.' : 'Lịch lặp được kiểm tra toàn bộ trước khi tạo.'} submitLabel={booking ? 'Lưu ca thuê' : 'Tạo lịch'} isSaving={saving}><div style={{ display: 'grid', gap: 12 }}>{error && <div className="rounded-lg bg-rose-50 p-3 text-sm font-bold text-rose-700">{error}</div>}<div className="grid gap-3 sm:grid-cols-2"><Input label="Tên lịch thuê" value={name} onChange={setName} required /><Select label="Chọn khách đã có" value={customerId} onChange={chooseCustomer} options={[{ value: '', label: 'Nhập khách mới bên dưới' }, ...customers.filter(c => c.status === 'active').map(c => ({ value: c.id, label: `${c.name} · ${c.phone}` }))]} /><Input label="Người thuê" value={renterName} onChange={setRenterName} required /><Input label="Số điện thoại" value={renterPhone} onChange={setRenterPhone} required /><Input label="Ngày bắt đầu" type="date" value={date} onChange={setDate} required /><Input label="Phòng" value="Phòng học" onChange={() => {}} disabled /><Input label="Giờ bắt đầu" value={startTime} onChange={setStartTime} required /><Input label="Giờ kết thúc" value={endTime} onChange={setEndTime} required /><Select label="Bảng giá gợi ý" value={planId} onChange={choosePlan} options={[{ value: '', label: 'Tự nhập đơn giá' }, ...(plans.length ? plans : defaultPlans).filter(p => p.status === 'active').map(p => ({ value: p.id || p.name, label: `${p.name} · ${money(p.amount)}` }))]} /><Input label="Đơn giá ca" type="number" value={amount} onChange={setAmount} suffix="đ" required /><Select label="Điều hòa" value={air} onChange={setAir} options={[{ value: 'no', label: 'Không dùng điều hòa' }, { value: 'yes', label: 'Dùng điều hòa' }]} /></div>{!booking && <div className="rounded-lg border border-slate-200 p-3"><div className="mb-2 text-xs font-black uppercase tracking-wide text-slate-500">Lịch lặp (tùy chọn)</div><div className="grid gap-3 sm:grid-cols-2"><Input label="Lặp đến ngày" type="date" value={repeatEnd} onChange={setRepeatEnd} /><div><div className="mb-1 text-xs font-bold text-slate-500">Các thứ trong tuần</div><div className="flex flex-wrap gap-1">{['T2', 'T3', 'T4', 'T5', 'T6', 'T7'].map((label, index) => <button key={label} type="button" onClick={() => setRepeatDays(v => v.includes(index + 1) ? v.filter(x => x !== index + 1) : [...v, index + 1])} className={`rounded-md border px-2 py-1 text-xs font-bold ${repeatDays.includes(index + 1) ? 'border-indigo-300 bg-indigo-50 text-indigo-700' : 'border-slate-200 text-slate-600'}`}>{label}</button>)}</div></div></div></div>}<label className="grid gap-1 text-xs font-bold text-slate-500">Ghi chú<textarea value={note} onChange={e => setNote(e.target.value)} rows={2} className="rounded-lg border border-slate-200 p-2 text-sm font-normal text-slate-800" /></label></div></ModalForm>;
}

function PaymentModal({ open, booking, paid, saving, onClose, onSave }: { open: boolean; booking: RentalBooking | null; paid: number; saving: boolean; onClose: () => void; onSave: (value: RentalPaymentInput) => Promise<void> }) { const [type, setType] = useState<'collection' | 'refund'>('collection'); const [amount, setAmount] = useState(String(Math.max((booking?.amount || 0) - paid, 0))); const [date, setDate] = useState(today()); const [method, setMethod] = useState<'cash' | 'bank'>('cash'); const [note, setNote] = useState(''); const max = type === 'refund' ? paid : Math.max((booking?.amount || 0) - paid, 0); const save = async () => { const value = Number(amount); if (!booking || value <= 0 || value > max) return; await onSave({ bookingId: booking.id, amount: value, date: ymdToDmy(date), method, note, transactionType: type }); onClose(); }; return <ModalForm open={open} onClose={onClose} onSubmit={save} title={type === 'refund' ? 'Ghi hoàn tiền' : 'Ghi khoản thu'} subtitle={booking ? `${booking.name} · còn/đã thu ròng: ${money(type === 'refund' ? paid : max)}` : ''} submitLabel="Ghi nhận" isSaving={saving}><div className="grid gap-3 sm:grid-cols-2"><Select label="Loại giao dịch" value={type} onChange={v => { setType(v as typeof type); setAmount(String(v === 'refund' ? paid : Math.max((booking?.amount || 0) - paid, 0))); }} options={[{ value: 'collection', label: 'Thu tiền' }, { value: 'refund', label: 'Hoàn tiền' }]} /><Input label="Ngày giao dịch" type="date" value={date} onChange={setDate} /><Input label={`Số tiền (tối đa ${money(max)})`} type="number" value={amount} onChange={setAmount} /><Select label="Hình thức" value={method} onChange={v => setMethod(v as typeof method)} options={[{ value: 'cash', label: 'Tiền mặt' }, { value: 'bank', label: 'Chuyển khoản' }]} /></div><label className="mt-3 grid gap-1 text-xs font-bold text-slate-500">Ghi chú<textarea value={note} onChange={e => setNote(e.target.value)} rows={2} className="rounded-lg border border-slate-200 p-2 text-sm font-normal" /></label></ModalForm>; }

export default function RoomRentalTab(props: { bookings: RentalBooking[]; payments: RentalPayment[]; customers: RentalCustomer[]; pricePlans: RentalPricePlan[]; loading: boolean; saving: boolean; onSaveBooking: (v: RentalBookingInput) => Promise<void>; onSavePayment: (v: RentalPaymentInput) => Promise<void>; onCancelBooking: (id: string) => Promise<void>; onCancelSeries: (id: string) => Promise<void>; onSaveCustomer: (v: Omit<RentalCustomer, 'createdAt' | 'updatedAt'>) => Promise<void>; onSavePricePlan: (v: RentalPricePlan) => Promise<void> }) {
  const { bookings, payments, customers, pricePlans, loading, saving } = props; const [view, setView] = useState<View>('overview'); const [month, setMonth] = useState(today().slice(0, 7)); const [bookingModal, setBookingModal] = useState(false); const [editing, setEditing] = useState<RentalBooking | null>(null); const [paying, setPaying] = useState<RentalBooking | null>(null); const [query, setQuery] = useState(''); const [customer, setCustomer] = useState<RentalCustomer | null>(null); const [price, setPrice] = useState<RentalPricePlan | null>(null);
  const active = bookings.filter(b => b.status !== 'cancelled'); const monthBookings = active.filter(b => dmyKey(b.date).startsWith(month)); const due = monthBookings.reduce((s, b) => s + b.amount, 0); const collected = payments.filter(p => dmyKey(p.date).startsWith(month)).reduce((s, p) => s + p.amount, 0); const outstanding = active.filter(b => dmyKey(b.date) <= today()).reduce((s, b) => s + paymentState(b, payments).balance, 0); const visible = [...bookings].filter(b => !query || `${b.name} ${b.renterName} ${b.renterPhone}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => `${dmyKey(a.date)}${a.startTime}`.localeCompare(`${dmyKey(b.date)}${b.startTime}`)); const openNew = () => { setEditing(null); setBookingModal(true); };
  const tabs = [{ id: 'overview', label: 'Tổng quan' }, { id: 'schedule', label: 'Lịch phòng' }, { id: 'bookings', label: 'Ca thuê' }, { id: 'customers', label: 'Khách thuê' }, { id: 'payments', label: 'Thu tiền' }, { id: 'reports', label: 'Báo cáo' }, { id: 'prices', label: 'Bảng giá' }];
  return <div className="grid gap-3"><PageToolbar title="Thuê phòng" actions={<Button icon={<Plus size={16} />} onClick={openNew}>Tạo lịch thuê</Button>}><ToolbarTabs tabs={tabs} active={view} onChange={v => setView(v as View)} /></PageToolbar>{view !== 'prices' && <div className="grid grid-cols-2 gap-2 lg:grid-cols-4">{[['Ca thuê tháng', String(monthBookings.length), 'text-indigo-700 bg-indigo-50'], ['Phải thu tháng', money(due), 'text-slate-700 bg-slate-100'], ['Đã thu tháng', money(collected), 'text-emerald-700 bg-emerald-50'], ['Còn phải thu đến nay', money(outstanding), 'text-amber-700 bg-amber-50']].map(([label, value, tone]) => <div key={String(label)} className="rounded-xl border border-slate-200 bg-white p-3"><div className="flex items-center gap-2 text-xs font-bold text-slate-500"><span className={`grid h-7 w-7 place-items-center rounded-lg ${tone}`}>•</span>{label}</div><div className="mt-2 truncate text-lg font-black text-slate-900">{value}</div></div>)}</div>}
    {view === 'overview' && <section className="grid gap-3 lg:grid-cols-2"><div className="rounded-xl border border-slate-200 bg-white p-4"><h3 className="m-0 text-sm font-black">Việc cần xử lý</h3><div className="mt-3 grid gap-2">{active.filter(b => paymentState(b, payments).balance > 0 && dmyKey(b.date) <= today()).slice(0, 6).map(b => <div key={b.id} className="flex items-center justify-between gap-2 rounded-lg bg-slate-50 p-2"><div><b className="text-sm">{b.name}</b><div className="text-xs text-slate-500">{b.date} · {b.startTime}–{b.endTime}</div></div><Button size="sm" variant="outline" intent="primary" onClick={() => setPaying(b)}>Thu {money(paymentState(b, payments).balance)}</Button></div>)}{!active.some(b => paymentState(b, payments).balance > 0 && dmyKey(b.date) <= today()) && <EmptyState text="Không có khoản cần thu" sub="Các ca đến hôm nay đã được đối soát." />}</div></div><div className="rounded-xl border border-slate-200 bg-white p-4"><h3 className="m-0 text-sm font-black">Quy ước vận hành</h3><ul className="mt-3 grid gap-2 pl-5 text-sm text-slate-600"><li>Ca hủy không chặn lịch và không tính phải thu.</li><li>Không xóa khoản thu; hoàn tiền là một giao dịch âm riêng.</li><li>Lịch lặp được kiểm tra toàn bộ trước khi lưu.</li><li>Thuê phòng không cộng vào học phí hay thu chi trung tâm.</li></ul></div></section>}
    {view === 'schedule' && <section className="rounded-xl border border-slate-200 bg-white"><div className="flex flex-wrap items-center justify-between gap-2 border-b border-slate-200 p-3"><b className="text-sm">Lịch phòng sắp tới</b><Input label="Từ khóa" value={query} onChange={setQuery} placeholder="Tên khách, SĐT" style={{ width: 220 }} /></div><div className="grid gap-2 p-3 md:grid-cols-2 xl:grid-cols-3">{visible.filter(b => b.status !== 'cancelled').slice(0, 24).map(b => <button key={b.id} type="button" onClick={() => { setEditing(b); setBookingModal(true); }} className="rounded-lg border border-slate-200 p-3 text-left hover:border-indigo-300"><div className="flex justify-between gap-2"><b>{b.name}</b><span className="text-xs text-slate-500">{b.date}</span></div><div className="mt-1 text-sm text-slate-600">{b.startTime}–{b.endTime} · {b.renterName}</div><div className="mt-2 text-xs font-bold text-amber-700">{paymentState(b, payments).label}</div></button>)}{!visible.length && <EmptyState text="Chưa có lịch thuê" sub="Tạo ca lẻ hoặc lịch lặp để bắt đầu." action={{ label: 'Tạo lịch', onClick: openNew }} />}</div></section>}
    {view === 'bookings' && <section className="rounded-xl border border-slate-200 bg-white"><div className="flex flex-wrap gap-2 border-b border-slate-200 p-3"><Input label="Tìm ca thuê" value={query} onChange={setQuery} placeholder="Tên lịch, khách, SĐT" style={{ width: 280 }} /></div><div className="grid gap-2 p-3">{visible.map(b => { const state = paymentState(b, payments); return <div key={b.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-slate-200 p-3"><div><div className="flex items-center gap-2"><b>{b.name}</b><StatusBadge status={b.status} label={statusLabel[b.status]} tone={b.status === 'cancelled' ? 'neutral' : b.status === 'completed' ? 'success' : 'primary'} /></div><div className="mt-1 text-sm text-slate-600">{b.date} · {b.startTime}–{b.endTime} · {b.renterName} ({b.renterPhone})</div><div className="mt-1 text-xs font-bold text-slate-500">{money(b.amount)} · {state.label}</div></div><div className="flex gap-1"><Button size="sm" variant="ghost" intent="primary" onClick={() => { setEditing(b); setBookingModal(true); }}>Sửa</Button><Button size="sm" variant="outline" intent="primary" disabled={b.status === 'cancelled'} onClick={() => setPaying(b)}>Thu tiền</Button>{b.status !== 'cancelled' && <Button size="sm" variant="ghost" intent="danger" onClick={() => { if (window.confirm('Hủy ca này? Lịch sử thu tiền vẫn được giữ.')) void props.onCancelBooking(b.id); }}>Hủy</Button>}{b.seriesId && b.status !== 'cancelled' && <Button size="sm" variant="ghost" intent="neutral" onClick={() => { if (window.confirm('Hủy các ca chưa diễn ra của lịch lặp này?')) void props.onCancelSeries(b.seriesId); }}>Hủy chuỗi</Button>}</div></div>; })}</div></section>}
    {view === 'customers' && <section className="rounded-xl border border-slate-200 bg-white p-3"><div className="mb-3 flex justify-end"><Button size="sm" icon={<Plus size={14} />} onClick={() => setCustomer({ id: '', name: '', phone: '', status: 'active', note: '' })}>Thêm khách</Button></div><div className="grid gap-2 md:grid-cols-2 xl:grid-cols-3">{customers.map(c => { const cb = bookings.filter(b => b.customerId === c.id || (!b.customerId && b.renterPhone === c.phone)); const balance = cb.reduce((s, b) => s + paymentState(b, payments).balance, 0); return <button key={c.id} type="button" onClick={() => setCustomer(c)} className="rounded-lg border border-slate-200 p-3 text-left"><b>{c.name}</b><div className="mt-1 text-sm text-slate-600">{c.phone}</div><div className="mt-2 text-xs font-bold text-slate-500">{cb.length} ca · còn {money(balance)}</div></button>; })}{!customers.length && <EmptyState text="Chưa có khách thuê" sub="Khách sẽ tự tạo khi lập lịch, hoặc thêm trước tại đây." />}</div></section>}
    {view === 'payments' && <section className="rounded-xl border border-slate-200 bg-white p-3"><div className="grid gap-2">{[...payments].sort((a, b) => dmyKey(b.date).localeCompare(dmyKey(a.date))).map(p => { const b = bookings.find(x => x.id === p.bookingId); return <div key={p.id} className="flex items-center justify-between rounded-lg border border-slate-200 p-3"><div><b className={p.amount < 0 ? 'text-rose-700' : 'text-emerald-700'}>{p.amount < 0 ? 'Hoàn tiền' : 'Thu tiền'} · {money(Math.abs(p.amount))}</b><div className="mt-1 text-sm text-slate-600">{p.date} · {b?.name || p.bookingId} · {p.method === 'bank' ? 'Chuyển khoản' : 'Tiền mặt'}</div>{p.note && <div className="mt-1 text-xs text-slate-500">{p.note}</div>}</div><MoneyText value={p.amount} tone={p.amount < 0 ? 'danger' : 'success'} /></div>; })}{!payments.length && <EmptyState text="Chưa có giao dịch" sub="Ghi thu hoặc hoàn tiền từ danh sách ca thuê." />}</div></section>}
    {view === 'reports' && <section className="rounded-xl border border-slate-200 bg-white p-4"><div className="mb-4 flex justify-end"><Input label="Tháng báo cáo" type="month" value={month} onChange={setMonth} style={{ width: 170 }} /></div>{[['Dự thu theo ca trong tháng', due], ['Thu ròng theo ngày giao dịch', collected], ['Còn phải thu đến hôm nay', outstanding]].map(([label, value]) => <div key={String(label)} className="flex justify-between border-t border-slate-100 py-3 text-sm"><b className="text-slate-600">{label}</b><MoneyText value={Number(value)} tone={String(label).includes('Còn') ? 'warning' : 'success'} /></div>)}<p className="mt-4 text-xs text-slate-500">Các chỉ số này chỉ đọc dữ liệu Thuê phòng; không được đưa vào báo cáo học phí hoặc thu chi của trung tâm.</p></section>}
    {view === 'prices' && <section className="rounded-xl border border-slate-200 bg-white p-3"><div className="mb-3 flex justify-end"><Button size="sm" icon={<Plus size={14} />} onClick={() => setPrice({ id: '', name: '', amount: 60000, durationMinutes: 90, airConditioning: false, status: 'active', order: pricePlans.length + 1, note: '' })}>Thêm bảng giá</Button></div><div className="grid gap-2 md:grid-cols-2">{(pricePlans.length ? pricePlans : defaultPlans).map(p => <button key={p.id || p.name} type="button" onClick={() => setPrice(p)} className="rounded-lg border border-slate-200 p-3 text-left"><b>{p.name}</b><div className="mt-1 text-sm text-slate-600">{money(p.amount)} · {p.durationMinutes} phút · {p.airConditioning ? 'Có điều hòa' : 'Không điều hòa'}</div><div className="mt-1 text-xs font-bold text-slate-500">{p.status === 'active' ? 'Đang áp dụng' : 'Ngừng áp dụng'}</div></button>)}</div></section>}
    <BookingModal key={`${bookingModal}-${editing?.id || 'new'}`} open={bookingModal} booking={editing} customers={customers} plans={pricePlans} saving={saving} allBookings={bookings} onClose={() => setBookingModal(false)} onSave={props.onSaveBooking} /><PaymentModal key={`${paying?.id || 'none'}-${!!paying}`} open={!!paying} booking={paying} paid={paying ? paymentState(paying, payments).paid : 0} saving={saving} onClose={() => setPaying(null)} onSave={props.onSavePayment} />
    <CustomerModal customer={customer} saving={saving} onClose={() => setCustomer(null)} onSave={props.onSaveCustomer} /><PriceModal price={price} saving={saving} onClose={() => setPrice(null)} onSave={props.onSavePricePlan} />
  </div>;
}

function CustomerModal({ customer, saving, onClose, onSave }: { customer: RentalCustomer | null; saving: boolean; onClose: () => void; onSave: (v: Omit<RentalCustomer, 'createdAt' | 'updatedAt'>) => Promise<void> }) { const [name, setName] = useState(customer?.name || ''); const [phone, setPhone] = useState(customer?.phone || ''); const [status, setStatus] = useState<RentalCustomer['status']>(customer?.status || 'active'); const [note, setNote] = useState(customer?.note || ''); return <ModalForm open={!!customer} onClose={onClose} onSubmit={async () => { if (!name || !phone) return; await onSave({ id: customer?.id || '', name, phone, status, note }); onClose(); }} title={customer?.id ? 'Cập nhật khách thuê' : 'Thêm khách thuê'} submitLabel="Lưu khách" isSaving={saving}><div className="grid gap-3 sm:grid-cols-2"><Input label="Họ tên" value={name} onChange={setName} /><Input label="Số điện thoại" value={phone} onChange={setPhone} /><Select label="Trạng thái" value={status} onChange={v => setStatus(v as RentalCustomer['status'])} options={[{ value: 'active', label: 'Đang dùng' }, { value: 'inactive', label: 'Ngừng dùng' }]} /></div><label className="mt-3 grid gap-1 text-xs font-bold text-slate-500">Ghi chú<textarea value={note} onChange={e => setNote(e.target.value)} rows={2} className="rounded-lg border border-slate-200 p-2 font-normal" /></label></ModalForm>; }
function PriceModal({ price, saving, onClose, onSave }: { price: RentalPricePlan | null; saving: boolean; onClose: () => void; onSave: (v: RentalPricePlan) => Promise<void> }) { const [name, setName] = useState(price?.name || ''); const [amount, setAmount] = useState(String(price?.amount || 60000)); const [duration, setDuration] = useState(String(price?.durationMinutes || 90)); const [air, setAir] = useState(price?.airConditioning ? 'yes' : 'no'); const [status, setStatus] = useState<RentalPricePlan['status']>(price?.status || 'active'); return <ModalForm open={!!price} onClose={onClose} onSubmit={async () => { if (!name || Number(amount) <= 0) return; await onSave({ id: price?.id || '', name, amount: Number(amount), durationMinutes: Number(duration) || 90, airConditioning: air === 'yes', status, order: price?.order || 1, note: price?.note || '' }); onClose(); }} title={price?.id ? 'Cập nhật bảng giá' : 'Thêm bảng giá'} submitLabel="Lưu bảng giá" isSaving={saving}><div className="grid gap-3 sm:grid-cols-2"><Input label="Tên bảng giá" value={name} onChange={setName} /><Input label="Đơn giá" type="number" value={amount} onChange={setAmount} /><Input label="Thời lượng (phút)" type="number" value={duration} onChange={setDuration} /><Select label="Điều hòa" value={air} onChange={setAir} options={[{ value: 'no', label: 'Không điều hòa' }, { value: 'yes', label: 'Có điều hòa' }]} /><Select label="Trạng thái" value={status} onChange={v => setStatus(v as RentalPricePlan['status'])} options={[{ value: 'active', label: 'Đang áp dụng' }, { value: 'inactive', label: 'Ngừng áp dụng' }]} /></div></ModalForm>; }
